Debug: true
HTTPBind: :8090
Slat: b10adc3749ba50cbbe76e057f20f8876
Mysql:
  DbDsn: root:123456@tcp(127.0.0.1:3306)/database_name?charset=utf8mb4
  ShowSql: true
Redis:
  RedisAddr: 127.0.0.1:7379
  Password: 123456
  RedisDb: 0
Logger:
  Path: ./log/echo-scaffolding.log
  MaxSize: 10240
  MaxAge: 7
  Compress: true
  LocalTime: true